FIND_PATH(
	SDL2_INCLUDE_DIR
	NAMES SDL.h SDL_main.h
	PATHS /usr/local/include/SDL2/
)

FIND_PATH(
	SDL2_BINARY_DIRS
	NAMES SDL2.lib SDL2main.lib
	PATHS /usr/local/lib/
)

FIND_LIBRARY(
	SDL2_LIBRARIES
	NAMES SDL2 SDL2main 
	PATHS /usr/local/lib/
)

IF (SDL2_INCLUDE_DIR AND SDL2_LIBRARIES AND SDL2_BINARY_DIRS)
    SET(SDL2_FOUND TRUE)
ENDIF (SDL2_INCLUDE_DIR AND SDL2_LIBRARIES AND SDL2_BINARY_DIRS)

IF (SDL2_FOUND)
    IF (NOT SDL2_FIND_QUIETLY)
        MESSAGE(STATUS "Found library: ${SDL2_LIBRARIES}")
    ENDIF (NOT SDL2_FIND_QUIETLY)
ELSE (SDL2_FOUND)
    IF (SDL2_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "SDL2 library")
    ENDIF (SDL2_FIND_REQUIRED)
ENDIF (SDL2_FOUND)
